import { type Product, type Profile } from './schema';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'whey-isolate',
    nameEn: 'Pure Isolate Whey Protein',
    nameFr: 'Protéine de Lactosérum Isolat Pure',
    descriptionEn: 'Ultra-filtered native whey isolate delivering 26g of pure protein per serving. Bio-luxe formulation for optimal muscle recovery.',
    descriptionFr: 'Isolat de lactosérum natif ultra-filtré apportant 26g de protéines pures par portion. Formulation bio-luxe pour une récupération musculaire optimale.',
    price: '49.99',
    priceCents: 4999,
    imageUrl: '/images/true-formula-whey.jpg',
    category: 'whey',
    flavors: ['Vanilla Bean', 'Dark Chocolate', 'Strawberry Cream', 'Unflavored'],
    sizes: ['1kg', '2.5kg'],
    stock: 150,
    popularityScore: 98,
    isFeatured: true,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'creatine-monohydrate',
    nameEn: 'Micronized Creatine Monohydrate',
    nameFr: 'Créatine Monohydrate Micronisée',
    descriptionEn: '100% pharmaceutical-grade micronized creatine monohydrate. Enhances explosive strength, muscle volume, and cellular hydration.',
    descriptionFr: "Créatine monohydrate micronisée 100% de qualité pharmaceutique. Améliore la force explosive, le volume musculaire et l'hydratation cellulaire.",
    price: '29.99',
    priceCents: 2999,
    imageUrl: '/images/true-formula-creatine.jpg',
    category: 'creatine',
    flavors: ['Unflavored', 'Blue Raspberry', 'Lemon Lime'],
    sizes: ['300g', '500g'],
    stock: 200,
    popularityScore: 92,
    isFeatured: true,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'marine-collagen',
    nameEn: 'Bio-Active Marine Collagen',
    nameFr: 'Collagène Marin Bio-Actif',
    descriptionEn: 'Sustainably sourced Type I & III hydrolyzed marine collagen peptides with hyaluronic acid and vitamin C for joint and skin elasticity.',
    descriptionFr: "Peptides de collagène marin hydrolysé Type I & III issus d'une pêche durable avec acide hyaluronique et vitamine C pour les articulations et la peau.",
    price: '39.99',
    priceCents: 3999,
    imageUrl: '/images/true-formula-collagen.jpg',
    category: 'wellness',
    flavors: ['Unflavored', 'Salted Caramel', 'Peach Iced Tea'],
    sizes: ['400g'],
    stock: 120,
    popularityScore: 88,
    isFeatured: true,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'protein-bar-box',
    nameEn: 'Artisanal Protein Crunch Bar (Box of 12)',
    nameFr: 'Barre Protéinée Crunch Artisanale (Boîte de 12)',
    descriptionEn: 'Gourmet triple-layered protein bar containing 20g protein and less than 2g sugar per bar. Crisp texture with natural cacao.',
    descriptionFr: 'Barre protéinée gourmande triple couche contenant 20g de protéines et moins de 2g de sucre par barre. Texture croustillante au cacao naturel.',
    price: '34.99',
    priceCents: 3499,
    imageUrl: '/images/true-formula-bar.jpg',
    category: 'snacks',
    flavors: ['Triple Chocolate', 'Salted Peanut Butter', 'Berry Crunch'],
    sizes: ['12 Bars'],
    stock: 80,
    popularityScore: 85,
    isFeatured: true,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'plant-protein',
    nameEn: 'Organic Plant Protein Blend',
    nameFr: 'Mélange de Protéines Végétales Bio',
    descriptionEn: 'Synergistic blend of fermented pea, organic pumpkin seed, and sacha inchi protein. Complete amino acid profile with smooth digestion.',
    descriptionFr: 'Mélange synergique de pois fermenté, graines de courge bio et sacha inchi. Profil complet en acides aminés et digestion douce.',
    price: '44.99',
    priceCents: 4499,
    imageUrl: '/images/true-formula-plant.jpg',
    category: 'plant',
    flavors: ['Vanilla Matcha', 'Chocolate Hazelnut'],
    sizes: ['900g'],
    stock: 95,
    popularityScore: 78,
    isFeatured: true,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'pre-workout',
    nameEn: 'Pre-Workout Bio-Energy Elixir',
    nameFr: 'Élixir Bio-Énergétique Pré-Entraînement',
    descriptionEn: 'Clean, jitter-free pre-workout formula with L-citrulline malate, beta-alanine, and natural green tea caffeine. Elevates focus and blood flow.',
    descriptionFr: 'Formule pré-entraînement propre sans tremblements avec L-citrulline malate, bêta-alanine et caféine naturelle de thé vert. Stimule le focus et le flux sanguin.',
    price: '38.99',
    priceCents: 3899,
    imageUrl: '/images/true-formula-preworkout.jpg',
    category: 'preworkout',
    flavors: ['Yuzu Citrus', 'Electric Watermelon'],
    sizes: ['400g'],
    stock: 110,
    popularityScore: 90,
    isFeatured: false,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: 'steel-shaker',
    nameEn: 'Apothecary Matte Steel Shaker (750ml)',
    nameFr: 'Shaker en Acier Mat Apothicaire (750ml)',
    descriptionEn: 'Double-wall insulated stainless steel shaker bottle. Keeps drinks cold for 24 hours. Leak-proof cap with silent agitation screen.',
    descriptionFr: 'Shaker isotherme en acier inoxydable à double paroi. Garde les boissons fraîches 24h. Bouchon étanche avec grille de mélange silencieuse.',
    price: '24.99',
    priceCents: 2499,
    imageUrl: '/images/true-formula-shaker.jpg',
    category: 'accessories',
    flavors: ['Matte Obsidian', 'Sage Green', 'Porcelain White'],
    sizes: ['750ml'],
    stock: 300,
    popularityScore: 75,
    isFeatured: false,
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
];

export const MOCK_PROFILES: Profile[] = [
  {
    id: '00000000-0000-4000-a000-000000000002',
    email: 'admin@proteinshop.com',
    fullName: 'Store Admin',
    role: 'admin',
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
  {
    id: '00000000-0000-4000-a000-000000000001',
    email: 'customer@example.com',
    fullName: 'Jane Doe',
    role: 'customer',
    createdAt: new Date('2026-01-01T00:00:00Z'),
  },
];
